[functions]
  directory = "netlify/functions"
  node_bundler = "esbuild"

[build]
  # 1 Génère humans.txt avant le build Astro
  # (si tu préfères via npm scripts, vois note en bas)
  command = "node src/scripts/generate-humans.js && astro build"
  publish = "dist"

[build.environment]
  NODE_VERSION = "20"

# 2 Cache agressif pour les assets Astro
[[headers]]
  for = "/_astro/*"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

# 3 humans.txt : NE PAS le mettre en cache (il change à chaque build)
[[headers]]
  for = "/humans.txt"
  [headers.values]
    Cache-Control = "no-cache, no-store, must-revalidate"

# 4 Sitemaps : alias/redirects vers l’index réel d’Astro
[[redirects]]
  from = "/sitemap.xml"
  to = "/sitemap-index.xml"
  status = 301
  force = true

[[redirects]]
  from = "/sitemap-site.xml"
  to = "/sitemap-index.xml"
  status = 301
  force = true

# 5 Préviews & branches : noindex
[context.deploy-preview]
  [[context.deploy-preview.headers]]
    for = "/*"
    [context.deploy-preview.headers.values]
      X-Robots-Tag = "noindex, nofollow"

[context.branch-deploy]
  [[context.branch-deploy.headers]]
    for = "/*"
    [context.branch-deploy.headers.values]
      X-Robots-Tag = "noindex, nofollow"
